gpu:
  batch_size: 50000
  blocks_per_sm: 0
  enabled: true
miner:
  api_url: https://mine.defensio.io/api
  max_workers: 1
  name: GPU-Miner
  version: 0.0.2
wallet:
  consolidate_address: null
  file: wallets.db
